# Generated by Django 5.2.2 on 2025-06-16 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='annee_sortie',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banque.categorie_film'),
        ),
        migrations.AlterField(
            model_name='film',
            name='realisateur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
