# Generated by Django 5.2.2 on 2025-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0002_alter_acteur_age_alter_film_annee_sortie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='affiche',
            field=models.ImageField(blank=True, null=True, upload_to='affiches/'),
        ),
    ]
