# Generated by Django 5.2.2 on 2025-06-17 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0003_alter_film_affiche'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='personnes',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='personne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='banque.personne'),
        ),
        migrations.AddField(
            model_name='film',
            name='acteurs',
            field=models.ManyToManyField(related_name='films', to='banque.acteur'),
        ),
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acteur',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='../photos/'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='commentaire',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='banque.film'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='note',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='film',
            name='affiche',
            field=models.ImageField(blank=True, null=True, upload_to='../affiches/'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='personne',
            name='mot_de_passe',
            field=models.CharField(max_length=128),
        ),
    ]
